name: Main Graduate workflow

on:
  push:
    branches:
      - main


jobs:
  assistant_app_test:
    name: Проверьте тест на приложение Ассистент
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
      - name: Проверьте репозиторий
        uses: actions/checkout@v3

      - name: Установите Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Устанавливать зависимости
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0
          pip install -r ./assistant/requirements.txt
          pip install -r ./assistant/tests/funct/requirements.txt

      - name: Тестирования на flake8
        run: python -m flake8 assistant/ --verbose

      - name: Копировать .env.example в .env
        run: cp $GITHUB_WORKSPACE/deploy/.env.example $GITHUB_WORKSPACE/deploy/.env

      - name: Запуск docker-compose
        run: docker compose -f deploy/docker-compose.yml up --build -d --remove-orphans

      - name: Ожидание готовности сервисов
        run: |
          echo "Ждем готовности базы данных..."
          while ! docker exec movies_db pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
            sleep 5
          done
          
          echo "Ждем готовности Elasticsearch..."
          while ! curl -fsSL "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"; do
            sleep 10
          done
           
          echo "Ждем готовности приложения..."
          until curl -f "http://localhost:8000/api/v1/healthcheck"; do
            sleep 10
          done
          
      - name: Тестирования приложение Ассистент
        run: PYTHONPATH=$GITHUB_WORKSPACE/assistant/tests/funct python -m pytest -v $GITHUB_WORKSPACE/assistant/tests/funct/src

